### ISSUE TITLE
we have a problem

### ISSUE THREAD

**Issue by cdcp998** [EnderExtreme/Rong-GT#18]
[crash-2019-05-14_22.04.13-server.txt](https://github.com/EnderExtreme/Rong-GT/files/3178137/crash-2019-05-14_22.04.13-server.txt)
[e.txt](https://github.com/EnderExtreme/Rong-GT/files/3178139/e.txt)

**Comment by Rongmario** [comment]
@cdcp998 可以試用一般的Forge Server嗎? 可能是Sponge搞怪。

**Comment by cdcp998** [comment]
会中文啊。。。不过建议弄成插件式吧，这样问题太多了。。

**Comment by cdcp998** [comment]
直接依赖GT启动就好。。

**Comment by Rongmario** [comment]
知道一點點而已，一般的GT可以跟Sponge共用嗎?

**Comment by cdcp998** [comment]
[e1.txt](https://github.com/EnderExtreme/Rong-GT/files/3178385/e1.txt)
Forge Server问题依旧。。。海绵可以正常启动GTCE。

**Comment by Rongmario** [comment]
好，回家看看，謝謝

**Comment by cdcp998** [comment]
错误少复制了一个 [22:46:43] [Server thread/INFO] [gregtech]: Registering recipes...

**Comment by Rongmario** [comment]
修好了, 正在上傳: https://minecraft.curseforge.com/projects/gregtech-chill-edition/files/2711140

**Comment by cdcp998** [comment]
[01:57:44] [Server thread/FATAL] [gregtech]: Seems like invalid recipe was found.
[01:57:44] [Server thread/FATAL] [gregtech]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[01:57:44] [Server thread/FATAL] [gregtech]: Ignoring invalid recipes and continuing loading!
[01:57:44] [Server thread/FATAL] [gregtech]: Some things may lack recipes or have invalid ones, proceed at your own risk
[01:57:44] [Server thread/FATAL] [gregtech]: Report to GregTech: Chill Edition's Github/Curse page to get help and fix the problem
[01:57:44] [Server thread/FATAL] [gregtech]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[01:57:27] [Server thread/ERROR] [gregtech]: Error happened during processing ore registration of prefix crushed and material uranium. Seems like cross-mod compatibility issue. Report to GTCE github.

- 

[01:58:06] [Server thread/WARN] [FML]: Registry Block: Override did not have an associated owner object. Name: tconstruct:molten_emerald Value: Block{minecraft:air}
[01:58:07] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
        at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549) ~[ForgeRegistry.class:?]
        at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:556) ~[GameData.class:?]
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:235) ~[GameData.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[01:58:07] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: E:\我的世界\宝可梦\.\crash-reports\crash-2019-05-15_01.58.07-server.txt
Forge Server错误[crash-2019-05-15_01.58.07-server.txt](https://github.com/EnderExtreme/Rong-GT/files/3179140/crash-2019-05-15_01.58.07-server.txt)
海绵错误[crash-2019-05-15_01.52.15-server.txt](https://github.com/EnderExtreme/Rong-GT/files/3179148/crash-2019-05-15_01.52.15-server.txt)

辛苦了。然而修复了1个问题。多了2个问题、，可能是MOD冲突。。
Forge Server 海绵 依旧。有时间慢慢解决  谢谢=。=让你辛苦了。

**Comment by cdcp998** [comment]
对了，问个问题 如果我用GTCE的存档，可以直接换GTChill Edition's而继续继承存档吗？

**Comment by Rongmario** [comment]
@cdcp998 可以開另一個github帖子嗎?

我沒有試過, 但我有換一些ID可能會起衝突
